version: "3.8"
services:
    nodeserver:
        build:
            context: ./app
        ports:
            - "3000:3000"
    nginx:
        restart: always
        build:
            context: ./nginx
        volumes:
            - ./nginx.conf:/etc/nginx/default.conf
        ports:
            - "81:80"
